# Travis configuration file
# Read more under http://docs.travis-ci.com/user/build-configuration/

# Set the build language to Python
language: python
jobs:
  include:
    - name: "Tests (Python 3.6)"
      python: 3.6
      env: TOXENV=py36
    - name: "Tests (Python 3.7)"
      python: 3.7
      env: TOXENV=py37
    - name: "Tests (Python 3.8)"
      python: 3.8
      env: TOXENV=py38
    - name: "Documentation"
      python: 3.6
      env: TOXENV=docs
    - name: "Benchmarks"
      python: 3.6
      env: TOXENV=benchmarks
install:
  - sudo apt-get install pandoc # pandoc for jupyter notebooks
  - sudo apt install graphviz # graphviz for class inheritance diagrams in docs
  - pip install tox
script:
  - tox
after_success:
  - bash <(curl -s https://codecov.io/bash) # upload test coverage to codecov
