# For more information about this pyproject.toml file, see
# PEP 518: https://www.python.org/dev/peps/pep-0518/


# Configuration of the black code style checker
# For more information about Black's usage of this file, see
# https://github.com/psf/black#pyprojecttoml
[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


[tool.pylint.messages_control]
# Exceptions suggested from Black: bad-continuation, bad-whitespace
disable = """
invalid-name,
fixme,

bad-continuation,

no-else-return,
no-else-raise,

no-member,

abstract-class-instantiated,
too-many-locals,
too-few-public-methods,
too-many-arguments,
unused-argument,
missing-module-docstring,
missing-function-docstring,
duplicate-code,
protected-access,
no-self-use,
arguments-differ,
attribute-defined-outside-init,
too-many-statements,
too-many-instance-attributes,
too-complex,
too-many-lines,
redefined-builtin,
abstract-method,
too-many-branches,
line-too-long,
missing-class-docstring,
unnecessary-pass,
unused-variable,
"""
# Many more `disable`s are defined in `./tox.ini` on a per-module basis!

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.master]
extension-pkg-whitelist = "numpy"
# Extensions that might be of interest in the future:
# pylint.extensions.docstyle,
# pylint.extensions.check_elif,
# pylint.extensions.docparams,
load-plugins = """
pylint.extensions.mccabe,
pylint.extensions.redefined_variable_type,
pylint.extensions.overlapping_exceptions,
"""

[tool.pylint.design]
max-complexity = "14"
